Combat.class: combat.java Informations.class Personnage.class
	javac combat.java

Informations.class: informations.java
	javac informations.java

Personnage.class: personnage.java
	javac personnage.java

run: Combat.class
	java Combat
