Combat.class: combat.java Informations.class Personnage.class
	javac combat.java

Informations.class: informations.java
	javac informations.java

Personnage.class: personnage.java Util.class
	javac personnage.java

Util.class: util.java
	javac util.java

run: Combat.class
	java Combat
