Piece.class: Piece.java
	javac Piece.java

Pion.class: Pion.java Piece.class
	javac Pion.java

Tour.class: Tour.java Piece.class
	javac Tour.java

Cavalier.class: Cavalier.java Piece.class
	javac Cavalier.java

Fou.class: Fou.java Piece.class
	javac Fou.java

Dame.class: Dame.java Piece.class
	javac Dame.java

Roi.class: Roi.java Piece.class
	javac Roi.java

Case.class: Case.java Piece.class
	javac Case.java
