Lanceur.class: Lanceur.java Plateau.class Joueur.class Jeu.class
	javac Lanceur.java

Plateau.class: Plateau.java
	javac Plateau.java

Joueur.class: Joueur.java
	javac Joueur.java

Jeu.class: Jeu.java
	javac Jeu.java

run: Lanceur.class
	java Lanceur
